### ISSUE TITLE
There's a  'T1' label on the Rungler schematic near R20...

### ISSUE THREAD

**Issue by Dav3xor** [kweiwen/benjolin#5]
From looking at your board layout, I think this is maybe leftover from something?  Thanks for publishing this btw!

**Comment by kweiwen** [comment]
hey @Dav3xor,

T1 means Transistor 1(BC547)

**Comment by Dav3xor** [comment]
Oh!  of course.  it's also a net label, so I don't feel totally brain dead.  Thanks.  I also assume the third pin of the switch is left unconnected?

**Comment by kweiwen** [comment]
@Dav3xor yes sir, there's many way to control the step.  check this site: http://modularsynthesis.com/hordijk/benjolin/benjolin.htm

**Comment by Dav3xor** [comment]
Hey, thanks for putting this on github, I designed my own pcb from your schematic, and I got it to work on the first try.
